stages:
  - build
  - package
  - Cross-Cloud
  - Cross-Project

before_script:
  - export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}
  - export CI_COMMIT_SHA_SHORT=$(echo ${CI_COMMIT_SHA} | cut -c -8)

compile:
  image: golang:1.8.1
  stage: build
  script:
    - ln -s /builds /go/src/github.com
    - cd /go/src/github.com/coredns/coredns
    - go get github.com/estesp/manifest-tool
    - go get github.com/progrium/gh-release
    - go get github.com/mholt/caddy
    - go get github.com/miekg/dns
    - go get golang.org/x/net/context
    - go get golang.org/x/text
    - make -j $(getconf _NPROCESSORS_ONLN)
        -f Makefile.release build
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 5 weeks
    paths:
      - build/Linux
      - build/linux/amd64

container:
  stage: package
  image: docker:17.05.0
  script:
    - IMAGE_TAG=${CI_COMMIT_REF_NAME}.${CI_COMMIT_SHA_SHORT}.${CI_JOB_ID}
    - cp build/Linux/coredns . || true
    - cp build/linux/amd64/coredns . || true
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    - echo export IMAGE=$CI_REGISTRY_IMAGE | tee release.env
    - echo export TAG=$IMAGE_TAG | tee -a release.env
    - cat release.env
  dependencies:
    - compile
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 5 weeks
    paths:
      - release.env

# Deploy Template used for Cross-Cloud API Call
.cross-cloud: &cross-cloud
  allow_failure: false
  image: buildpack-deps:stretch
  stage: Cross-Cloud
  # variables:
  #   KUBERNETES_BRANCH: MUST BE SET
  #   CLOUD: MUST BE SET
  script:
    - >
      if [ "$BUILD_TRIGGER" == "yes" ]; then
        exit 0
      else
        apt update && apt install -y jq
        PROJECT_PIPELINE=$(curl -X POST -F token=$CROSS_CLOUD_CI_JOB_TOKEN -F ref=stable-v0.2.0-integrations -F "variables[BRANCH]="${CLOUD_BRANCH}"" -F "variables[COMMIT]="${CLOUD_COMMIT}"" -F "variables[SOURCE]="${CI_PIPELINE_ID}"" -F "variables[DISABLE_SOURCE]="${CLOUD_DISABLE_SOURCE}"" -F "variables[ORG]=kubernetes" -F "variables[PROJECT]=kubernetes" -F "variables[PROJECT_ID]=14" -F "variables[PROJECT_TOKEN]="${KUBERNETES_PROJECT_TOKEN}"" -F "variables[CLOUD]="${CLOUD}"" "$BASE_URL"/api/v4/projects/2/trigger/pipeline | jq '.id')
        # PROJECT_PIPELINE=$(curl -X POST -F token=$CI_JOB_TOKEN -F ref=stable-v0.2.0-integrations https://gitlab.cncf.ci/api/v4/projects/2/trigger/pipeline | jq '.id')

        echo 'Wait for Cluster "FIX ME / HACK"'
        until [ "$PIPELINE_STATUS" == '"success"' ]; do
            PIPELINE_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "${BASE_URL}/api/v4/projects/2/pipelines/${PROJECT_PIPELINE}" | jq '.status')"
            sleep 0.5
            if [ $"PIPELINE_STATUS" == '"failed"' ]; then
                exit 1
            elif [ $"PIPELINE_STATUS" == '"canceled"' ]; then
                exit 1
            else
                continue
            fi
        done
        echo 'Cluster Ready'

        PROJECT_JOB=$(curl --header "PRIVATE-TOKEN:${TOKEN}" "${BASE_URL}/api/v4/projects/2/pipelines/${PROJECT_PIPELINE}/jobs?scope=success" | jq '.[] | select(.name=="Kubernetes-Deploy") | .id')

        export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}
        curl -s -o kubeconfig -L "$BASE_URL/cncf/cross-cloud/-/jobs/${PROJECT_JOB}/artifacts/raw/data/$CLOUD/kubeconfig"
        cat ./kubeconfig | base64 | tee ./kubeconfig

      fi
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 5 weeks
    paths:
      - kubeconfig


# Deploy Template used for Cross-Project API Call
.cross-project: &cross-project
  allow_failure: false
  image: buildpack-deps:stretch
  stage: Cross-Project
  # variables:
    # COREDNS_BRANCH: CAN BE SET
    # COREDNS_COMMIT: CAN BE SET
    # CLOUD: MUST BE SET
  script:
    - >
      if [ "$BUILD_TRIGGER" == "yes" ]; then
        exit 0
      else
        echo 'Trigger Cross-Project'
        apt update && apt install -y jq
        KUBECONFIG=$(cat ./kubeconfig | tr -d '\n')
        PROJECT_PIPELINE=$(curl -X POST -F token=$CROSS_PROJECT_CI_JOB_TOKEN -F ref=multi-project -F "variables[BRANCH]="${PROJECT_BRANCH}"" -F "variables[COMMIT]="${PROJECT_COMMIT}"" -F "variables[SOURCE]="${CI_PIPELINE_ID}"" -F "variables[DISABLE_SOURCE]="${PROJECT_DISABLE_SOURCE}"" -F "variables[KUBECONFIG]="${KUBECONFIG}"" -F "variables[ORG]="${CI_PROJECT_NAMESPACE}"" -F "variables[PROJECT]="${CI_PROJECT_NAME}"" -F "variables[PROJECT_ID]="${CI_PROJECT_ID}"" -F "variables[PROJECT_TOKEN]="${COREDNS_PROJECT_TOKEN}"" -F "variables[IMAGE_ARGS]=image.repository" -F "variables[TAG_ARGS]=image.tag" -F "variables[LABEL_ARGS]=-l k8s-app=coredns" -F "variables[FILTER]=.items[0].spec.containers[0].image" -F "variables[CHART]=coredns" -F "variables[NAME]=coredns" -F "variables[CHART_REPO]=stable" "$BASE_URL"/api/v4/projects/45/trigger/pipeline | jq '.id')
        # PROJECT_PIPELINE=$(curl -X POST -F token=$CI_JOB_TOKEN -F ref=master https://gitlab.cncf.ci/api/v4/projects/45/trigger/pipeline | jq '.id')

        echo 'Verify Project Deployment'

        until [ "$JOB_STATUS" == '"success"' ]; do
            JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "${BASE_URL}/api/v4/projects/45/pipelines/${PROJECT_PIPELINE}/jobs" | jq '.[] | select(.name=="Cross-Project") | .status')"
            sleep 0.5
            if [ $"JOB_STATUS" == '"failed"' ]; then
                exit 1
            elif [ $"JOB_STATUS" == '"canceled"' ]; then
                exit 1
            else
                continue
            fi
        done
        echo 'Deployment Successful'
      fi
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 5 weeks
    paths:
      - kubeconfig


Cross-Cloud:
  <<: *cross-cloud

Cross-Project:
  <<: *cross-project
